interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Authorization:
      - CyberWatch APIAuth-HMAC-SHA256 dEJijBfLnJ6OBIqV8SXvSsFhY1d7RlH7wRaUiy4ESiE=:PrhYjSjBAnwyBwxkwNfedZp5IXqmfgAnKwKRB3HEVZs=
      Connection:
      - keep-alive
      Date:
      - Mon, 22 Feb 2021 08:47:11 GMT
      User-Agent:
      - python-requests/2.22.0
    method: GET
    uri: https://localhost/api/v3/vulnerabilities/cve_announcements/wrong_id
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAAw3KsQqAIBAG4FeRf2lxaHByC6GxdxC9Isg70LNFfPf65m+AapUKP5AkE7xbnUXT
        qL3B4xA1u3TOsCjUWrz+giD9ybyoOW/OJry0Mf8pUSFWzPkBF0CLXVUAAAA=
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 22 Feb 2021 08:47:11 GMT
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      - Accept
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - SAMEORIGIN
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Request-Id:
      - 986aaac8-5ab8-48d8-87cd-cdb207d83e9d
      X-Runtime:
      - '0.008302'
      X-XSS-Protection:
      - 1; mode=block
    status:
      code: 404
      message: Not Found
version: 1
